import dotenv from "dotenv"
dotenv.config()
import express from "express"
import cors from "cors"
import { inference } from "./utils/hf.js"

const app = express()
app.use(express.json()) // Using express.json() instead of bodyParser.json()
app.use(cors())

app.post("/api/generate-offer", async (req, res) => {
  try {
    const { request } = req.body
    const aboutTask = `
You will receive from a user the type of web application he wants to build. Below is the template on which you should formulate the answer. Make sure your answer to the client follows this template and is well written. The template:

I. Purpose of the Document:
This preliminary offer is based on the information you have provided. Before we can start the actual development and provide you with an accurate estimate of costs and time required, we will need to go through a few essential planning stages:
• Development of a logical diagram to define the application architecture.
• Creation of an ER diagram to structure the database.
• Creation of an initial design in Figma to eliminate any ambiguity related to the graphical interface.
To begin these stages, it will be necessary to sign a collaboration contract and pay in advance for these services:
• Logical diagram and ER diagram: X Euro + VAT
• Figma project: X Euro + VAT
These amounts will be deducted from the total development price once the firm offer is accepted. The offer below is only indicative and aims to give you an overview of how we operate and the probable costs. For an exact offer and implementation time, we will need to complete the aforementioned planning stages.


II. Proposed Structure:
[you will list here the tech stack that should be used and how would they help]

[next you will write the document structure outline on how it should be implemented]

III. Additional Suggestions:
[Description of suggested additional functionalities, including estimated duration and number of programmers]

IV. Price and Implementation Time:
Estimated Delivery Time: [Basic development and/or additional suggestions: total number of hours and estimated price]
The delivery time is influenced by the complexity of the project and your requirements. We will work closely with you to meet the established deadlines.

Under the current offer, you will benefit from the services of two programmers specialized in the programming language required for your project, a project manager who will design and coordinate the project, as well as a graphic designer responsible for creating the user/application interface. Each team in our company has the support of a mentor, who is responsible for overseeing and assisting the programmers. The price for this team is X Euro per hour.

Purchase Terms: This offer is strictly confidential. Veziv IT Services SRL does not grant permission to share details with third parties. Prices are excluding VAT.

The user instructions:`

    const allSent = {
      model: "mistralai/Mistral-7B-Instruct-v0.3", // Specify the AI model
      messages: [
        {
          role: "user",
          content: `${aboutTask} \n ${request}`, // Fixed variable name from aboutMe to aboutTask and message.message to request
        },
      ],
      max_tokens: 5000, // Limit the maximum number of tokens generated by the model
    }

    const out = await inference.chatCompletion(allSent)
    // Return a response with status code 200
    res.status(200).json({
      message: out.choices[0].message.content,
    })
  } catch (error) {
    // Catch block to handle errors
    console.error("Error:", error)
    res.status(500).json({ error: "Internal Server Error" })
  }
})

app.listen(process.env.PORT, () => {
  console.log(`Server running on port ${process.env.PORT}`)
})
